# Generated by Django 4.2.7 on 2023-11-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=50, unique=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords', to='products.product')),
            ],
        ),
    ]
