# Generated by Django 4.2.7 on 2023-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_remove_keyword_products_keyword_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='entry',
            field=models.CharField(max_length=50),
        ),
    ]
