# Generated by Django 4.2.7 on 2023-11-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('slug', models.CharField(max_length=127, unique=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=30)),
                ('visit_number', models.IntegerField(default=0)),
                ('collection', models.CharField(max_length=100)),
                ('sale', models.BooleanField(default=False)),
                ('spotlight', models.BooleanField(default=False)),
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_styles.product_style')),
            ],
        ),
    ]
